
apiVersion: v1
kind: Pod
metadata:
  name: mariadb-1-tmpfs
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb
    image: hyperhq/mariadb-arm64v8:10.3-1
    resources:
      limits:
        memory: 1024Mi
    ports:
    - name: mysql-port
      containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    - name: MYSQL_DATABASE
      value: "test"
    - name: MYSQL_USER
      value: "test"
    - name: MYSQL_PASSWORD
      value: "test"
